# lint-elisp.yml
---

name: Lint Emacs Lisp
on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    name: Emacs Lint
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version: [29.4]
        experimental: [false]
        include:
          - os: ubuntu-latest
            emacs-version: snapshot
            experimental: true
          - os: macos-latest
            emacs-version: snapshot
            experimental: true
          - os: windows-latest
            emacs-version: snapshot
            experimental: true
    steps:
      - name: setenv
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

        # Install Emacs
      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

        # Install Cask
      - uses: conao3/setup-cask@master
        with:
          version: 'snapshot'

      - name: Install dependencies with Cask
        run: "cask install"

      - name: Print HOME and locate package-lint
        run: |
          cask exec emacs --batch -Q \
                --eval "(progn
                  (prin1 (getenv \"HOME\"))
                  (prin1 (file-name-directory (locate-library \"package-lint\"))) )"

      - name: Byte-compile Emacs config
        run: |
          emacs --batch -Q \
                -f batch-byte-compile init.el early-init.el || exit 1
        working-directory: ${{ github.workspace }}


      - name: Lint Emacs Lisp files with package-lint
        run: |
          cask exec emacs --batch -Q \
            --eval "(progn
              (require 'seq)
              (require 'package-lint)
              (let ((files
                    (seq-filter
                     (lambda (f)
                       (not (string-match-p \"/\\\\(\\\\.cask\\\\|elpa\\\\|node_modules\\\\|dist\\\\)/\" f)))
                     (directory-files-recursively \"./\" \"\\\\.el$\"))))
                (dolist (file files)
                  (with-temp-buffer
                    (insert-file-contents file)
                    (package-lint-buffer file)))))"
        working-directory: ${{ github.workspace }}

      - name: Checkdoc on Emacs Lisp files
        run: |
          cask exec emacs --batch -Q \
                --eval "(progn
                  (require 'checkdoc)
                  (dolist (file (directory-files-recursively \"./\" \"\\.el$\"))
                    (find-file file)
                    (unless (checkdoc nil t)
                      (kill-emacs 1))))"
        working-directory: ${{ github.workspace }}
